# Generated by Django 4.1.7 on 2024-05-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="img",
            field=models.CharField(default="fa-shopping-cart", max_length=70),
            preserve_default=False,
        ),
    ]
