# Generated by Django 4.1.7 on 2023-03-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_category_info_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="amt_left",
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
        migrations.AlterField(
            model_name="category",
            name="budget",
            field=models.FloatField(default=0),
        ),
    ]
