# Generated by Django 4.1.7 on 2023-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_alter_category_amt_left_alter_category_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="amt_left",
            field=models.FloatField(default=0),
        ),
    ]
